# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1Bo_mmKCopvEUTN7dZqTYgIbcneQqHc
"""

import pandas as pd
from prophet import Prophet

data = pd.read_csv("https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv")
trip_data = data[['Timestamp','trips']]
trip_data.date = pd.to_datetime(trip_data.Timestamp, infer_datetime_format=True)
trip_data = pd.DataFrame(trip_data.values, columns = ['ds','y'])
trip_data

m = Prophet(changepoint_prior_scale=0.5)

m.fit(trip_data)

#future = m.make_future_dataframe(periods=100)
pred = m.make_future_dataframe(freq='H',periods=744)
model = m.predict(pred)

modelFit = m.plot(model)